config/routes.rb
Rails.application.routes.draw do
  resources :members
  devise_for :users
  devise_scope :user do
  		get 'sign_in', to: 'devise/sessions#new'
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get "home", to: "spages#home"
    #root 'spages#home'
      get ":spage" => "spages#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    #@member = Member.new
   @member = current_user.members.build
  
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = current_user.members.build(member_params)
    #@member = Member.new(member_params)
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email_id, :phone_no, :phone_no2, :address, :available)
    end
end

app/controllers/spages_controller.rb
class SpagesController < ApplicationController

	def show
    	render template: "spages/#{params[:spage]}"
  	end

  	def home
    end
  	def electrician	
	end

	def plumber 
		  layout 'application' 

	end

	def lock_smith		
	end

	def wild_ranger 		
	end

	def towig_van		
	end

	def carpenter 		
	end


	def baby_sitter 		
	end

	def Pest_control
	end

	def painter
	end

	def club
	end

	def coaching
	end

	def city_info
	end

	def othr_service
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/spages_helper.rb
module SpagesHelper
end

app/views/layouts/_calender.html.erb
<center>
<script language="javascript" type="text/javascript">
var day_of_week = new Array('Sun','Mon','Tue','Wed','Thu','Fri','Sat');
var month_of_year = new Array('January','February','March','April','May','June','July','August','September','October','November','December');

//  DECLARE AND INITIALIZE VARIABLES
var Calendar = new Date();

var year = Calendar.getFullYear();     // Returns year
var month = Calendar.getMonth();    // Returns month (0-11)
var today = Calendar.getDate();    // Returns day (1-31)
var weekday = Calendar.getDay();    // Returns day (1-31)

var DAYS_OF_WEEK = 7;    // "constant" for number of days in a week
var DAYS_OF_MONTH = 31;    // "constant" for number of days in a month
var cal;    // Used for printing

Calendar.setDate(1);    // Start the calendar day at '1'
Calendar.setMonth(month);    // Start the calendar month at now

/* VARIABLES FOR FORMATTING
NOTE: You can format the 'BORDER', 'BGCOLOR', 'CELLPADDING', 'BORDERCOLOR'
      tags to customize your caledanr's look. */

var TR_start = '<TR>';
var TR_end = '</TR>';
var highlight_start = '<TD WIDTH="30"><TABLE CELLSPACING=0 BORDER=1 BGCOLOR=DEDEFF BORDERCOLOR=CCCCCC><TR><TD WIDTH=20><B><CENTER>';
var highlight_end   = '</CENTER></TD></TR></TABLE></B>';
var TD_start = '<TD WIDTH="30"><CENTER>';
var TD_end = '</CENTER></TD>';

/* BEGIN CODE FOR CALENDAR
NOTE: You can format the 'BORDER', 'BGCOLOR', 'CELLPADDING', 'BORDERCOLOR'
tags to customize your calendar's look.*/

cal =  '<TABLE BORDER=1 CELLSPACING=0 CELLPADDING=0 BORDERCOLOR=BBBBBB><TR><TD>';
cal += '<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=2>' + TR_start;
cal += '<TD COLSPAN="' + DAYS_OF_WEEK + '" BGCOLOR="#EFEFEF"><CENTER><B>';
cal += month_of_year[month]  + '   ' + year + '</B>' + TD_end + TR_end;
cal += TR_start;

//   DO NOT EDIT BELOW THIS POINT  //

// LOOPS FOR EACH DAY OF WEEK
for(index=0; index < DAYS_OF_WEEK; index++)
{

// BOLD TODAY'S DAY OF WEEK
if(weekday == index)
cal += TD_start + '<B>' + day_of_week[index] + '</B>' + TD_end;

// PRINTS DAY
else
cal += TD_start + day_of_week[index] + TD_end;
}

cal += TD_end + TR_end;
cal += TR_start;

// FILL IN BLANK GAPS UNTIL TODAY'S DAY
for(index=0; index < Calendar.getDay(); index++)
cal += TD_start + '  ' + TD_end;

// LOOPS FOR EACH DAY IN CALENDAR
for(index=0; index < DAYS_OF_MONTH; index++)
{
if( Calendar.getDate() > index )
{
  // RETURNS THE NEXT DAY TO PRINT
  week_day =Calendar.getDay();

  // START NEW ROW FOR FIRST DAY OF WEEK
  if(week_day == 0)
  cal += TR_start;

  if(week_day != DAYS_OF_WEEK)
  {

  // SET VARIABLE INSIDE LOOP FOR INCREMENTING PURPOSES
  var day  = Calendar.getDate();

  // HIGHLIGHT TODAY'S DATE
  if( today==Calendar.getDate() )
  cal += highlight_start + day + highlight_end + TD_end;

  // PRINTS DAY
  else
  cal += TD_start + day + TD_end;
  }

  // END ROW FOR LAST DAY OF WEEK
  if(week_day == DAYS_OF_WEEK)
  cal += TR_end;
  }

  // INCREMENTS UNTIL END OF THE MONTH
  Calendar.setDate(Calendar.getDate()+1);

}// end for loop

cal += '</TD></TR></TABLE></TABLE>';

//  PRINT CALENDAR
document.write(cal);

//  End -->
</script>
</center>

app/views/layouts/_count.html.erb
 <center>
    <h5 style="color: #666; font-weight: 100;font-size: 30px; margin: 40px 0px 20px;">UPDATED IN </h5>
    <div id="clockdiv" style="font-family: sans-serif; color: #fff;display: inline-block; font-weight: 100;text-align: center;font-size: 20px;">
      <div>
        <span class="days" ></span>
        <div class="smalltext" style="padding-top: 5px;font-size: 16px;">Days</div>
      </div>
      <div>
        <span class="hours"></span>
        <div class="smalltext" style="padding-top: 5px;font-size: 16px;">Hours</div>
      </div>

      </br>
      </br>
      <div>
        <span class="minutes"></span>
        <div class="smalltext" style="padding-top: 5px;font-size: 16px;">Minutes</div>
      </div>
      <div>
        <span class="seconds"></span>
        <div class="smalltext" style="padding-top: 5px;font-size: 16px;">Seconds</div>
      </div>
    </div>
<!--        <script type="text/javascript" src="clock.js"></script>  -->
 
    <script type="text/javascript" >
       function getTimeRemaining(endtime) {
            var t = Date.parse(endtime) - Date.parse(new Date());
            var seconds = Math.floor((t / 1000) % 60);
            var minutes = Math.floor((t / 1000 / 60) % 60);
            var hours = Math.floor((t / (1000 * 60 * 60)) % 24);
            var days = Math.floor(t / (1000 * 60 * 60 * 24));
            return {
              'total': t,
              'days': days,
              'hours': hours,
              'minutes': minutes,
              'seconds': seconds
            };
          }

          function initializeClock(id, endtime) {
            var clock = document.getElementById(id);
            var daysSpan = clock.querySelector('.days');
            var hoursSpan = clock.querySelector('.hours');
            var minutesSpan = clock.querySelector('.minutes');
            var secondsSpan = clock.querySelector('.seconds');

            function updateClock() {
              var t = getTimeRemaining(endtime);

              daysSpan.innerHTML = t.days;
              hoursSpan.innerHTML = ('0' + t.hours).slice(-2);
              minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);
              secondsSpan.innerHTML = ('0' + t.seconds).slice(-2);

              if (t.total <= 0) {
                clearInterval(timeinterval);
              }
            }

            updateClock();
            var timeinterval = setInterval(updateClock, 1000);
          }

          var deadline = new Date(Date.parse(new Date()) + 07 * 24 * 60 * 60 * 1000);
          initializeClock('clockdiv', deadline);
        </script>
</center>

app/views/layouts/_footer.html.erb
 
      <!-- Start Footer Section -->
      <footer>
        <div class="container">
          <div class="row footer-widgets">
            <!-- Start Contact Widget -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="footer-widget contact-widget">
                <h4>
                  <img src="assets/images/mlogo.png" class="img-responsive" alt="Footer Logo" />
                </h4>
                <p>
                <h3> "Stretch Until You Smile"</h3></p><p>
                  To create a better every day life for the many people in our city </p>
              </div>
            </div>
            <!-- End Contact Widget -->

            <!-- Start latest Work Posts Widget -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="footer-widget flickr-widget">
                <h4>
                  Latest Work
                </h4>
                <ul class="flickr-list">
                  <li>
                    <a href="assets/img/work/img-1.jpg" class="lightbox">
                    <img alt="" src="assets/img/work/img-1.jpg" alt="pravin">
                    </a>
                  </li>
                  <li>
                    <a href="assets/img/work/img-2.jpg" class="lightbox">
                    <img alt="" src="assets/img/work/img-2.jpg">
                    </a>
                  </li>
                  <li>
                    <a href="assets/img/work/img-3.jpg" class="lightbox">
                    <img alt="" src="assets/img/work/img-3.jpg">
                    </a>
                  </li>
                  <li>
                    <a href="assets/img/work/img-4.jpg" class="lightbox">
                    <img alt="" src="assets/img/work/img-4.jpg">
                    </a>
                  </li>
                  <li>
                    <a href="assets/img/work/img-5.jpg" class="lightbox">
                    <img alt="" src="assets/img/work/img-5.jpg">
                    </a>
                  </li>
                  <li>
                    <a href="assets/img/work/img-6.jpg" class="lightbox">
                    <img alt="" src="assets/img/work/img-6.jpg">
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <!-- End latest Work  Widget -->

            <!-- Start Address Widget -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="footer-widget">
                <h4>
                  KCity Office
                </h4>
                <ul class="address">
                  <li>
                    <a>
                    <i class="fa fa-map-marker"></i> Vrundavan Society Karjat </a>
                  </li>
                  <li><a>
                    <i class="fa fa-phone"></i> (90217) 27849, (89831)17595    </a>
             
                   </li>
                  <li><a>
                    <i class="fa fa-envelope"></i> Pdhumak.11@gmail.com</a>

                  </li>
                  <li><a>
                    <i class="fa fa-fax"></i> FAX:(123) 123-4567</a>

                  </li>
                </ul>
              </div>
            </div>
            <!-- End Address Widget -->

            <!-- Start Text Widget -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="footer-widget hours-widget">
                <h4>
                  Business Hours
                </h4>
                <div class="contact-info">
                  <p>Our support available to help you 24 hours a day, seven days a week.</p>
                  <ul class="hours">
                    <li>Monday-Friday: <span>9am to 5pm</span></li>
                    <li>Saturday: <span>10am to 3pm</span></li>
                    <li>Sunday: <span>Closed</span></li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- End Text Widget -->

          </div>
          <!-- .row -->        
        </div>



      <!-- Start Copyright -->
      <div class="copyright-section">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <p>
                Copyright &copy; 2017 KCity - Designed & Developed by 
                <a href="https://goo.gl/4g53q1" target="_blank">
                Pdhumak11
                </a>
              </p>
            </div>
          </div>
          <!-- .row -->
        </div>
      </div>
      <!-- End Copyright -->
      
      </footer>
      <!-- End Footer Section -->

app/views/layouts/_header.html.erb
 <!-- Start Header Section -->
      <header id="header-wrap" class="site-header clearfix">
        <!-- Start Top Bar -->
        <div class="top-bar hidden-xs">
          <div class="container">
            <div class="row">
              <div class="col-md-7 col-sm-9">
                <!-- Start Contact Info -->
                <ul class="contact-details">
                  <li>
                    <a href="contact_us" target="_blank">
                    <i class="icon-envelope">
                    </i>
                     Pdhumak.11@gmail.com
                    </a>
                  </li>
                  <li>
                    <a href="contact_us" target="_blank">
                    <i class="icon-call-out">
                    </i>
                    Call Us: (9021) 727- 849
                    </a>
                  </li>  
                  <li>
                    <a href="contact_us" target="_blank">
                    <i class="icon-clock">
                    </i>
                    Sun-Sat <span class="timing">(9am-5pm)</span>
                    </a>
                  </li>                
                </ul>
                <!-- End Contact Info -->
              </div>
              <div class="col-md-5 col-sm-3">
                <!-- Start Social Links -->
                <ul class="social-list">
                  <li>
                    <a href="https://goo.gl/vdfSGR" class="social-link facebook" data-toggle="tooltip" data-placement="bottom" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
                  </li>
                  <li>
                    <a href="https://twitter.com/PdhumakP?p=s" class="social-link twitter" data-toggle="tooltip" data-placement="bottom" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>
                  </li>
                  <li>
                    <a href="https://goo.gl/JejNSG" class="social-link google" data-toggle="tooltip" data-placement="bottom" title="Google Plus" target="_blank"><i class="fa fa-google-plus"></i></a>
                  </li>
                  <li>
                    <a href="https://dribbble.com/Pdhumak11" class="social-link dribbble" data-toggle="tooltip" data-placement="bottom" title="Dribble" target="_blank" ><i class="fa fa-dribbble"></i></a>
                  </li>
                  <li>
                    <a href="https://goo.gl/sQ6ZUi" class="social-link linkdin" data-toggle="tooltip" data-placement="bottom" title="Linkedin" target="_blank"><i class="fa fa-linkedin"></i></a>
                  </li>
                </ul>
                <!-- End Social Links -->
              </div>
            </div>
          </div>
        </div>
        <!-- End Top Bar -->

        <!-- Start  Logo & Navigation  -->
        <div class="navbar navbar-default navbar-top" role="navigation" data-spy="affix" data-offset-top="50">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <!-- Stat Toggle Nav Link For Mobiles -->
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <!-- End Toggle Nav Link For Mobiles -->
              <div class="logo-wrapper">
                <a class="navbar-brand" href="https://goo.gl/4g53q1" target="_blank">
                  <img src="assets/images/mlogo.png" alt="KCityService">
                </a>  
              </div>
            </div>
            <!--  Brand and toggle menu for mobile ends  -->

            <div class="navbar-collapse collapse">
              <!-- Stat Search -->
              <div class="search-side">
                <a class="show-search">
                <i class="icon-magnifier"></i>
                </a>
              </div>
              <!-- Form for navbar search area -->
              <form class="full-search">
                <div class="container">
                  <div class="row">
                    <input class="form-control" type="text" placeholder="Search...">
                    <a class="close-search">
                    <span class="fa fa-times fa-2x">
                    </span>
                    </a>
                  </div>
                </div>
              </form>
              <!-- Search form ends -->

              <!-- Start Navigation List -->
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <a class="active" href="home">
                  Home
                  </a>
                 </li>
                <li>
                  <a href="electrician">
                  Services
                  </a>
                  <ul class="dropdown">
                    <li>
                      <a href="electrician">
                      Electritian
                      </a>
                    </li>
                    <li>
                      <a href="plumber">
                      Plumber
                      </a>
                    </li>
                    <li>
                      <a href="pest_control">
                      Pest Control
                      </a>
                    </li>
                    <li>
                      <a href="painter">
                      Painter/ Carpainter 
                      </a>
                    </li>
                    <li>
                      <a href="wild_ranger">
                      Wild Ranger
                      </a>
                    </li>
                    <li>
                      <a href="lock_smith">
                      LockSmith
                      </a>
                    </li>
                    <li>
                      <a href="baby_sitter">
                      BabySitter
                      </a>
                    </li>
                  </ul>
                </li>

                <li>
                  <a href="city_info">
                  Our City
                  </a>
                  <ul class="dropdown">
                    <li>
                      <a href="city_info">
                      About City
                      </a>
                    </li>
                    <li>
                      <a href="city_info">
                      History & Spots
                      </a>
                    </li>
                    <li>
                      <a href="http://raigad.nic.in/karjat/htmldocs/contact.html">
                      IMP Number
                      </a>
                    </li>
      
                  </ul>
                </li>

                <li>
                  <a href="contact.html">
                  Calender
                  </a>
                    <ul class="dropdown">
                    <li>
                      <a href="services.html">
                         <%= render partial: "layouts/calender" %>
                      </a>
                    </li>
                    </ul>

                </li>

                <li><a href="othr_service">Other Services</a>
                  <ul class="dropdown">
                    <li>
                      <a href="clubs">
                        Clubs
                      </a>
                    </li>
                    <li>
                      <a href="coaching">
                        Coaching
                      </a>
                    </li>
                    <li>
                      <a href="404.html">
                      Intirior Design
                      </a>
                    </li>
                  </ul>
                </li>
               
                <li>
                 <!-- <a href="users/sign_in"> -->
                 <%= link_to 'New Member', new_member_path(@member)%>
    
                       <ul class="dropdown">
                    <li>
                         <%= render partial: "layouts/count" %>
                      
                    </li></ul>

                </li>

                <li>
                  <a href="about">
                  Contact
                  </a>
                </li>

              </ul>
              <!-- End Navigation List -->
            </div>
          </div>

          <!-- Mobile Menu Start -->
                    <!-- PRAVIN COPY FROM UPPER AND SET HERE AFTER ALL SET UP -->

          <ul class="wpb-mobile-menu">
            <li>
              <a class="active" href="home">
              Home
              </a>
              <ul class="dropdown">
                <li>
                  <a href="index-02.html">
                  Home 2
                  </a>
                </li>
                <li>
                  <a href="index-03.html">
                  Home 3
                  </a>
                </li>
                <li>
                  <a href="index-04.html">
                  Home 4
                  </a>
                </li>
                <li>
                  <a href="index-05.html">
                  Home 5
                  </a>
                </li>
              </ul>
            </li>
            <li>
              <a href="features.html">
              Features
              </a>
            </li>
            <li>
              <a href="#">
              Company
              </a>
              <ul class="dropdown">
                <li>
                  <a href="about.html">
                  About Us
                  </a>
                </li>
                <li>
                  <a href="certifications.html">
                  Certifications
                  </a>
                </li>
                <li>
                  <a href="company-history.html">
                  Company History
                  </a>
                </li>
                <li>
                  <a href="partners.html">
                  Our Partners
                  </a>
                </li>
                <li>
                  <a href="team.html">
                  Our Team
                  </a>
                </li>
                <li>
                  <a href="careers.html">
                  Careers
                  </a>
                </li>
                <li>
                  <a href="Pricing.html">
                  Pricing
                  </a>
                </li>
                <li>
                  <a href="faq.html">
                  FAQ
                  </a>
                </li>
                 <li>
                  <a href="404.html">
                  404
                  </a>
                </li>
              </ul>
            </li>
            <li><a href="services.html">Services</a>
              <ul class="dropdown">
                <li>
                  <a href="services.html">
                    All Services
                  </a>
                </li>
                <li>
                  <a href="services1.html">
                  Services Layout 01
                  </a>
                </li>
                <li>
                  <a href="services2.html">
                  Services Layout 02
                  </a>
                </li>
              </ul>
            </li>
            <li>
              <a href="projects.html">
              Projects
              </a>
              <ul class="dropdown">
                <li>
                  <a href="projects.html">
                  Projects layout 1 - Full Width
                  </a>
                </li>
                <li>
                  <a href="projects-2.html">
                  Projects layout 2 - Boxed 1
                  </a>
                </li>
                <li>
                  <a href="projects-3.html">
                  Projects layout 3 - Boxed 3
                  </a>
                </li>
                <li>
                  <a href="single-project.html">
                  Single Project
                  </a>
                </li>
              </ul>
            </li>
            <li>
              <a href="blog.html">
              Blog
              </a>
              <ul class="dropdown">
                <li>
                  <a href="blog.html">
                  Blog - Right sidebar
                  </a>
                </li>
                <li>
                  <a href="blog-left-sidebar.html">
                  Blog - Left Sidebar
                  </a>
                </li>
                <li><a href="blog-full-width.html">Blog - Full Width</a></li>
                <li>
                  <a href="single-post.html">
                  Single Post
                  </a>
                </li>
              </ul>
            </li>
            <li><a href="shop.html">Shop</a></li>
            <li>
              <a href="contact.html">
              Contact
              </a>
            </li>
          </ul>
          <!-- Mobile Menu End -->

        </div>
        <!-- End Header Logo & Navigation -->
        <div class="clearfix"></div>
      </header>
      <!-- End Header Section -->

app/views/layouts/_slider.html.erb
<!-- Start Content Section -->
      <section id="content" class="error-bg">
    <!--    <div class="container">
          <div class="row">
              <div class="error-page"> -->

                  <div id="sliderFrame">
        <div id="slider">
            <a href="assets/images/sd05">
                <img src="assets/images/sd01.jpg" alt="DOn't Panic SOLUTION of HomeWork is Here" />
            </a>
            <a class="lazyImage" href="assets/images/sd02.jpg" title="All Neccesury work Find Here"> All Neccesury work Find Here</a>
            <a href="http://www.menucool.com/javascript-image-slider">
                <b data-src="assets/images/sd03.jpg" data-alt="#htmlcaption3">Webservice Available 24 X 7</b>
            </a>
            <a class="lazyImage" href="assets/images/sd04.jpg" title="All Type Of Pest Control.">All Type Of Pest Control</a>
            <a class="lazyImage" href="assets/images/sd05.jpg" title="#htmlcaption5">
                Our Licencesed Electririan Can Keep Your Home Safe</a>
            <a class="lazyImage" href="assets/images/sd06.jpg" title="Plumbing Available For Repair Mainting and Installing">Plumbing Available For Repair Mainting and Installing</a>
            <a class="lazyImage" href="assets/images/sd07.jpg" title="Don't Harm Animal, Call Free of Animal Friend">Don't Harm Animal, Call Free of Animal Friend</a>
            <a class="lazyImage" href="assets/images/sd08.jpg" title="Carpainter or Painter For Modification Our Home ">Carpainter or Painter For Modification Our Home</a>
        </div>
       <div style="display: none;">
            <div id="htmlcaption3">
                <em>Webservice</em> available for <a href="http://www.menucool.com/">24 x 7</a>.
            </div>
            <div id="htmlcaption5">
                Our Licencesed Electririan Can Keep Your Home Safe
            </div>
        </div> 
                
        <!--thumbnails-->
        <div id="thumbs">
            <div class="thumb"><img src="assets/images/sd01.jpg" /></div>
            <div class="thumb"><img src="assets/images/sd02.jpg" /></div>
            <div class="thumb"><img src="assets/images/sd03.jpg" /></div>
            <div class="thumb"><img src="assets/images/sd04.jpg" /></div>
            <div class="thumb"><img src="assets/images/sd05.jpg" /></div>
            <div class="thumb"><img src="assets/images/sd06.jpg" /></div>
            <div class="thumb"><img src="assets/images/sd07.jpg" /></div>
            <div class="thumb"><img src="assets/images/sd08.jpg" /></div>
        </div>
    </div>
    </section

      <!-- End Content Section  -->

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p><center>

<h1>Members</h1>

<table >
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone no</th>
      <th>Phone no2</th>
      <th>Address</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email_id %></td>
        <td><%= member.phone_no %></td>
        <td><%= member.phone_no2 %></td>
        <td><%= member.address %></td>
        <td><%= member.available %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>
</center>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email_id %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @member.phone_no %>
</p>

<p>
  <strong>Phone no2:</strong>
  <%= @member.phone_no2 %>
</p>

<p>
  <strong>Address:</strong>
  <%= @member.address %>
</p>

<p>
  <strong>Available:</strong>
  <%= @member.available %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/spages/club.html.erb
<center>
	<h1>CLUBS</h1>
</center>

app/views/spages/coching.html.erb
<center>
	<h1>COACHING</h1>
</center>